
import javax.swing.JOptionPane;
import oru.inf.InfException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sofia
 */
public class Lager extends javax.swing.JFrame {

    /**
     * Creates new form Lager
     */
    public Lager() {
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUppdateraHattlager = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        btnSeHattar = new javax.swing.JButton();
        btnSeMaterialLagerStatus = new javax.swing.JButton();
        btnUppsateraMateriallager = new javax.swing.JButton();
        lblHattar = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUppdateraHattlager.setText("Uppdatera hattlager");
        btnUppdateraHattlager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraHattlagerActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSeHattar.setText("Se hattar i lager");
        btnSeHattar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeHattarActionPerformed(evt);
            }
        });

        btnSeMaterialLagerStatus.setText("Se lagerstatus för material i lager");
        btnSeMaterialLagerStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeMaterialLagerStatusActionPerformed(evt);
            }
        });

        btnUppsateraMateriallager.setText("Uppdatera materiallager");
        btnUppsateraMateriallager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppsateraMateriallagerActionPerformed(evt);
            }
        });

        lblHattar.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblHattar.setText("Hattar");

        lblMaterial.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMaterial.setText("Material");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbaka)
                    .addComponent(lblMaterial)
                    .addComponent(lblHattar)
                    .addComponent(btnUppdateraHattlager)
                    .addComponent(btnUppsateraMateriallager)
                    .addComponent(btnSeHattar)
                    .addComponent(btnSeMaterialLagerStatus))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHattar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeHattar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUppdateraHattlager)
                .addGap(41, 41, 41)
                .addComponent(lblMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeMaterialLagerStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUppsateraMateriallager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUppdateraHattlagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraHattlagerActionPerformed
        setVisible(false);
        new HattLager().setVisible(true);
    }//GEN-LAST:event_btnUppdateraHattlagerActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        setVisible(false);
        new Meny().setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSeHattarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeHattarActionPerformed
       setVisible(false);
        new SeHattarILager().setVisible(true);
    }//GEN-LAST:event_btnSeHattarActionPerformed

    private void btnSeMaterialLagerStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeMaterialLagerStatusActionPerformed
       setVisible(false);
        new SeLagerstatusMaterial().setVisible(true);
    }//GEN-LAST:event_btnSeMaterialLagerStatusActionPerformed

    private void btnUppsateraMateriallagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppsateraMateriallagerActionPerformed
        setVisible(false);
        new ÄndraLagerstatusMaterial().setVisible(true);
    }//GEN-LAST:event_btnUppsateraMateriallagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeHattar;
    private javax.swing.JButton btnSeMaterialLagerStatus;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnUppdateraHattlager;
    private javax.swing.JButton btnUppsateraMateriallager;
    private javax.swing.JLabel lblHattar;
    private javax.swing.JLabel lblMaterial;
    // End of variables declaration//GEN-END:variables
}
